CREATE TABLE Wallets (
    acc_no BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1011 INCREMENT BY 1) PRIMARY KEY,
    user_id INT REFERENCES Users(user_id), 
    balance DECIMAL(10, 2) DEFAULT 0.00 CHECK (balance >= 0), 
    status VARCHAR(20) DEFAULT 'ACTIVE',
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);